# Copyright (c) Omar Boukli-Hacene. All rights reserved.
# Distributed under an MIT-style license that can be
# found in the LICENSE file.

# SPDX-License-Identifier: MIT

trigger:
  branches:
    include:
      - "*"

strategy:
  matrix:
    linux_node_maintenance:
      imageName: ubuntu-latest
      node_version: 18.x
    linux_node_lts:
      imageName: ubuntu-latest
      node_version: 20.x
    linux_node_current:
      imageName: ubuntu-latest
      node_version: 21.x
    macos_node_lts:
      imageName: macOS-latest
      node_version: 20.x
    windows_node_lts:
      imageName: windows-latest
      node_version: 20.x

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: Set up Node.js

  - task: Npm@1
    inputs:
      command: custom
      customCommand: config set fund=false --global
    displayName: Configure NPM

  - task: Npm@1
    inputs:
      command: custom
      customCommand: install --global npm@latest
    displayName: Update NPM

  - task: Npm@1
    inputs:
      command: ci
    displayName: Install packages

  - task: Npm@1
    inputs:
      command: custom
      customCommand: run build
    displayName: Build

  - task: Npm@1
    inputs:
      command: custom
      customCommand: test
    displayName: Run tests

  - task: Npm@1
    inputs:
      command: custom
      customCommand: exec montehall -- --version
    displayName: Run smoke test
