strategy:
  matrix:
    linux_node_lts:
      imageName: ubuntu-latest
      node_version: 16.x
    linux_node_current:
      imageName: ubuntu-latest
      node_version: 18.x
    mac_node_current:
      imageName: macOS-latest
      node_version: 18.x
    windows_node_current:
      imageName: windows-latest
      node_version: 18.x

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

  - script: |-
      node --version
      npm --version
    displayName: Node.js and npm version

  - script: npm ci
    displayName: Build

  - script: npm test
    displayName: Run tests
