# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- develop

strategy:
  matrix:
    linux_node_8_x:
      imageName: 'ubuntu-16.04'
      node_version: 8.x
    linux_node_10_x:
      imageName: 'ubuntu-16.04'
      node_version: 10.x
    linux_node_11_x:
      imageName: 'ubuntu-16.04'
      node_version: 11.x
    mac_node_8_x:
      imageName: 'macOS-10.13'
      node_version: 8.x
    mac_node_10_x:
      imageName: 'macOS-10.13'
      node_version: 10.x
    mac_node_11_x:
      imageName: 'macOS-10.13'
      node_version: 11.x
    windows_node_8_x:
      imageName: 'windows-2019'
      node_version: 8.x
    windows_node_10_x:
      imageName: 'windows-2019'
      node_version: 10.x
    windows_node_11_x:
      imageName: 'windows-2019'
      node_version: 11.x

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

- script: |
    node --version
    npm --version
    npm ci
    npm test
  displayName: 'build'
