name: Build and test

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18.x
          - 19.x

    steps:
      - name: Check our repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm ci

      - name: Check code style
        run: npx prettier --check .

      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm test

      - name: Run integration tests
        run: |-
          npm run montehall -- --version
          npm run montehall -- --help
          npm run montehall
          npm run montehall -- --games 11
          npm run montehall -- --random advanced
          npm run montehall -- --wise
          npm run montehall -- --random advanced --wise
          npm run montehall -- --games 0 --random advanced --wise
          npm run montehall -- --games 3 --random advanced --wise --verbose
          npm run montehall -- --games 100 --table-file vendor/numbers.txt
          npm run montehall -- --games 100 --table-file vendor/numbers.txt --wise
          npm run montehall -- --doors 100 --games 100
          npm run montehall -- --doors 100 --games 100 --wise
          npm run montehall -- --doors 100 --games 3 --wise --verbose
