name: Build and test

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18.x
          - 19.x

    steps:
      - name: Check our repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm ci

      - name: Check code style
        run: npx prettier --check .

      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm test

      - name: Pack
        id: pack_artifact
        run: >-
          echo "artifact_name="$(
          npm pack --json --pack-destination ${{ runner.temp }}
          | jq --raw-output '.[0] | .filename'
          )""
          >> $GITHUB_OUTPUT

      - name: Install
        run: npm install --global ${{ steps.pack_artifact.outputs.artifact_name }}
        working-directory: ${{ runner.temp }}

      - name: Run integration tests
        run: |-
          montehall --version
          montehall --help
          montehall
          montehall --games 11
          montehall --random advanced
          montehall --wise
          montehall --random advanced --wise
          montehall --games 0 --random advanced --wise
          montehall --games 3 --random advanced --wise --verbose
          montehall --games 100 --table-file vendor/numbers.txt
          montehall --games 100 --table-file vendor/numbers.txt --wise
          montehall --doors 100 --games 100
          montehall --doors 100 --games 100 --wise
          montehall --doors 100 --games 3 --wise --verbose
        working-directory: ${{ github.workspace }}/..
