# Copyright (c) Omar Boukli-Hacene. All rights reserved.
# Distributed under an MIT-style license that can be
# found in the LICENSE file.

# SPDX-License-Identifier: MIT

name: Lint

on:
  push:
    paths:
      - "**.md"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-latest

    steps:
      - name: Use latest Node.js LTS
        uses: actions/setup-node@v3
        with:
          cache: npm
          check-latest: false
          node-version: lts/*

      - name: Install markdownlint-cli
        run: npm install --global markdownlint-cli

      - name: Check out code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Run markdownlint
        run: markdownlint .
